batch_size: 4
num_epochs: 3
lr: 0.0001
image_size: [224, 224]

model:
  encoder: clip-vit-base
  decoder: unet

dataset:
  train_json: data/vizwiz/train_grounding.json
  image_root: data/vizwiz/train
  mask_root: data/vizwiz/binary_masks_png/train