batch_size: 4
num_epochs: 10

lr: 0.0001
image_size: [224, 224]

model:
  encoder: resnet18
  decoder: unet

dataset:
  train_json: data/train_grounding.json
  val_json: data/val_grounding.json  
  train_image_root: data/train  
  train_mask_root: data/binary_masks_png/train  
  val_image_root: data//val            
  val_mask_root: data/binary_masks_png/val 