batch_size: 8
num_epochs: 10
lr: 0.0001
image_size: [224, 224]

model:
  encoder: clip-vit-large-patch14
  decoder: unet

dataset:
  train_json: data/vizwiz/train_grounding.json
  image_root: data/vizwiz/train
  mask_root: data/vizwiz/binary_masks_png/train